spring:
  application:
    name: cities-searcher
  datasource:
    url: jdbc:postgresql://localhost:5432/nominatim
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 500
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

search-cities:
  amount-handled-points-to-save-state: 10

server:
  servlet:
    context-path: /cities-searcher

nominatim:
  millis-between-requests: 10

search-mileage:
  load-city-geometries-on-start-application: false
